development:
  adapter: postgresql
  encoding: unicode
  database: ciclovias_joinville
  pool: 5
  username: lucas
  password: potato

test:
  adapter: postgresql
  encoding: unicode
  database: ciclovias_joinville
  pool: 5
  username: lucas
  password: potato

production:
  adapter: postgresql
  encoding: unicode
  database: ciclovias_joinville
  pool: 5
  username: lucas
  password: potato

teste:
  adapter: postgresql
  encoding: unicode
  database: ciclovias_joinville
  pool: 5
  username: lucas
  password: potato
